CREATE TABLE IF NOT EXISTS lookups (
  lookup_id serial PRIMARY KEY,
  lookup_type varchar(255),
  lookup_name varchar(255),
  lookup_hide boolean NOT NULL DEFAULT FALSE,
  lookup_ref_id int,
  lookup_notes varchar(255)
);

INSERT INTO lookups (lookup_id, lookup_type, lookup_name, lookup_hide, lookup_ref_id, lookup_notes) VALUES
(1, 'id_type', 'KP Lama', false, NULL, NULL),
(2, 'id_type', 'MyKad/MyKid', false, NULL, NULL),
(3, 'id_type', 'Passport', false, NULL, NULL),
(4, 'id_type', 'Penduduk Tetap', false, NULL, NULL),
(5, 'id_type', 'PolisNo. Kad Polis/Tentera', false, NULL, NULL),
(6, 'id_type', 'No. Sijil Beranak', false, NULL, NULL),
(7, 'id_type', 'UNHCR', false, NULL, NULL),
(8, 'marital_status', 'Bujang', false, NULL, NULL),
(9, 'marital_status', 'Berkahwin', false, NULL, NULL),
(10, 'marital_status', 'Ibu Tinggal', false, NULL, NULL),
(11, 'marital_status', 'Duda (Bercerai)', false, NULL, NULL),
(12, 'marital_status', 'Duda (Kematian Isteri)', false, NULL, NULL),
(13, 'marital_status', 'Ibu Tunggal (Bercerai)', false, NULL, NULL),
(14, 'marital_status', 'Balu (Kematian Suami)', false, NULL, NULL),
(15, 'race', 'Melayu', false, NULL, NULL),
(16, 'race', 'Cina', false, NULL, NULL),
(17, 'race', 'India', false, NULL, NULL),
(18, 'race', 'Lain-lain', false, NULL, NULL),
(19, 'religion', 'Islam', false, NULL, NULL),
(20, 'religion', 'Buddha', false, NULL, NULL),
(21, 'religion', 'Hindu', false, NULL, NULL),
(22, 'religion', 'Kristian', false, NULL, NULL),
(23, 'religion', 'Lain-lain', false, NULL, NULL),
(24, 'gender', 'Lelaki', false, NULL, NULL),
(25, 'gender', 'Perempuan', false, NULL, NULL),
(26, 'state', 'Selangor', false, NULL, NULL),
(27, 'district', 'Petaling', false, NULL, NULL),
(28, 'district', 'Klang', false, NULL, NULL),
(29, 'district', 'Gombak', false, NULL, NULL),
(30, 'district', 'Hulu Langat', false, NULL, NULL),
(31, 'district', 'Kuala Selangor', false, NULL, NULL),
(32, 'district', 'Sabak Bernam', false, NULL, NULL),
(33, 'district', 'Hulu Selangor', false, NULL, NULL),
(34, 'district', 'Sepang', false, NULL, NULL),
(35, 'district', 'Kuala Langat', false, NULL, NULL),
(36, 'address_type', 'Rumah', false, NULL, NULL),
(37, 'address_type', 'Pejabat', false, NULL, NULL),
(38, 'address_type', 'Sekolah', false, NULL, NULL),
(39, 'address_type', 'Lain-lain', false, NULL, NULL),
(40, 'education_type', 'UPSR', false, NULL, 'edu_category_1'),
(41, 'education_type', 'SRP/PMR', false, NULL, 'edu_category_2'),
(42, 'education_type', 'PT3', false, NULL, 'edu_category_2'),
(43, 'education_type', 'SPM', false, NULL, 'edu_category_2'),
(44, 'education_type', 'Diploma', false, NULL, 'edu_category_3'),
(45, 'education_type', 'Ijazah Sarjana', false, NULL, 'edu_category_3'),
(46, 'education_type', 'Ijazah', false, NULL, 'edu_category_3'),
(47, 'education_type', 'PhD', false, NULL, 'edu_category_3'),
(48, 'relationship', 'Ibu', false, NULL, NULL),
(49, 'relationship', 'Bapa', false, NULL, NULL),
(50, 'relationship', 'Adik-beradik', false, NULL, NULL),
(51, 'relationship', 'Pasangan', false, NULL, NULL),
(52, 'relationship', 'Lain-lain', false, NULL, NULL),
(53, 'status', 'Aktif', false, NULL, NULL),
(54, 'status', 'Tidak Aktif', false, NULL, NULL),
(55, 'status', 'Hapus', true, NULL, NULL),
(56, 'goods_type', 'Elektronik', false, NULL, NULL),
(57, 'goods_type', 'Pakaian & Aksesori', false, NULL, NULL),
(58, 'goods_type', 'Barangan Rumah & Perabot', false, NULL, NULL),
(59, 'goods_type', 'Kecantikan & Penjagaan Diri', false, NULL, NULL),
(60, 'goods_type', 'Makanan & Minuman', false, NULL, NULL),
(61, 'goods_type', 'Buku & Alat Tulis', false, NULL, NULL),
(62, 'goods_type', 'Sukan', false, NULL, NULL),
(63, 'goods_type', 'Permainan', false, NULL, NULL),
(64, 'goods_type', 'Automotif', false, NULL, NULL),
(65, 'goods_type', 'Kesihatan', false, NULL, NULL),
(66, 'job_types', 'Bekerja', false, NULL, NULL),
(67, 'job_types', 'Tidak Bekerja', false, NULL, NULL),
(68, 'job_types', 'Pelajar', false, NULL, NULL),
(69, 'bantuan_types', 'Tunai', false, NULL, NULL),
(70, 'bantuan_types', 'Barang', false, NULL, NULL),
(71, 'bantuan_categories', 'Fakir', false, NULL, NULL),
(72, 'bantuan_categories', 'Miskin', false, NULL, NULL),
(73, 'bantuan_categories', 'Bukan Fakir/Miskin', false, NULL, NULL),
(74, 'frequency_bantuan', 'Kaunter', false, NULL, NULL),
(75, 'frequency_bantuan', 'Sekali', false, NULL, NULL),
(76, 'frequency_bantuan', 'Berkala', false, NULL, NULL),
(77, 'frequency_bantuan', 'Berulang', false, NULL, NULL),
(78, 'recurring_options', 'Harian', false, NULL, NULL),
(79, 'recurring_options', 'Mingguan', false, NULL, NULL),
(80, 'recurring_options', 'Bulanan', false, NULL, NULL),
(81, 'recurring_options', 'Tahunan', false, NULL, NULL),
(85, 'kariah', 'Masjid Jamek Sultan Abdul Aziz, Petaling Jaya', false, 27, NULL),
(86, 'kariah', 'Masjid Jamek As-Solihin, Taman Tun Dr. Ismail', false, 27, NULL),
(87, 'kariah', 'Masjid Al-Ehsan, Bandar Kinrara', false, 27, NULL),
(88, 'kariah', 'Masjid Al-Falah, Subang Jaya', false, 27, NULL),
(89, 'kariah', 'Masjid Sultan Sulaiman, Klang', false, 28, NULL),
(90, 'kariah', 'Masjid Al-Hidayah, Kampung Rantau Panjang', false, 28, NULL),
(91, 'kariah', 'Masjid Nurul Ehsan, Taman Sentosa', false, 28, NULL),
(92, 'kariah', 'Masjid Ar-Rahman, Bukit Kuda', false, 28, NULL),
(93, 'kariah', 'Masjid Jamek Al-Amaniah, Batu Caves', false, 29, NULL),
(94, 'kariah', 'Masjid Zakaria, Gombak Setia', false, 29, NULL),
(95, 'kariah', 'Masjid Al-Syarif, Kuang', false, 29, NULL),
(96, 'kariah', 'Masjid Kampung Nakhoda', false, 29, NULL),
(97, 'kariah', 'Masjid Al-Hasanah, Bandar Baru Bangi', false, 30, NULL),
(98, 'kariah', 'Masjid Jamek Kajang', false, 30, NULL),
(99, 'kariah', 'Masjid Al-Mustaqim, Taman Cheras Jaya', false, 30, NULL),
(100, 'kariah', 'Masjid Jamek Kg Sungai Tangkas, Bangi', false, 30, NULL),
(101, 'kariah', 'Masjid Jamek Sultan Ibrahim, Kuala Selangor', false, 31, NULL),
(102, 'kariah', 'Masjid Al-Mutaqqin, Puncak Alam', false, 31, NULL),
(103, 'kariah', 'Masjid As-Salam, Puncak Alam', false, 31, NULL),
(104, 'kariah', 'Masjid At-Taufikiah, Bestari Jaya', false, 31, NULL),
(105, 'kariah', 'Masjid Jamek Makmuriah, Sabak Bernam', false, 32, NULL),
(106, 'kariah', 'Masjid An-Nur, Sungai Besar', false, 32, NULL),
(107, 'kariah', 'Masjid Asy-Syakirin, Sekinchan', false, 32, NULL),
(108, 'kariah', 'Masjid Al-Falah, Kampung Sungai Haji Dorani', false, 32, NULL),
(109, 'kariah', 'Masjid Jamek Ar-Rahman, Kuala Kubu Bharu', false, 33, NULL),
(110, 'kariah', 'Masjid Al-Khairiah, Hulu Yam Lama', false, 33, NULL),
(111, 'kariah', 'Masjid As-Salam, Bukit Sentosa', false, 33, NULL),
(112, 'kariah', 'Masjid Al-Hidayah, Sungai Choh', false, 33, NULL),
(113, 'kariah', 'Masjid Sultan Abdul Samad, KLIA', false, 34, NULL),
(114, 'kariah', 'Masjid Putra Perdana, Putra Perdana', false, 34, NULL),
(115, 'kariah', 'Masjid Kampung Salak Tinggi', false, 34, NULL),
(116, 'kariah', 'Masjid Ar-Rahman, Sungai Pelek', false, 34, NULL),
(117, 'kariah', 'Masjid Jamek Sultan Hisamuddin, Banting', false, 35, NULL),
(118, 'kariah', 'Masjid At-Taqwa, Banting', false, 35, NULL),
(119, 'kariah', 'Masjid Ar-Rahman, Telok Panglima Garang', false, 35, NULL),
(120, 'kariah', 'Masjid Jamek Al-Mubarakah, Kampung Sungai Manggis', false, 35, NULL),
(121, 'district', 'Batu Caves', false, NULL, NULL),
(122, 'state', 'Kuala Lumpur', true, NULL, NULL),
(123, 'state', 'Penang', true, NULL, NULL),
(124, 'state', 'Negeri Sembilan', true, NULL, NULL),
(125, 'state', 'Pahang', true, NULL, NULL),
(126, 'state', 'Sarawak', true, NULL, NULL),
(127, 'state', 'Sabah', true, NULL, NULL),
(128, 'state', 'Perak', true, NULL, NULL),
(129, 'state', 'Johor', true, NULL, NULL),
(130, 'state', 'Kedah', true, NULL, NULL),
(131, 'state', 'Kelantan', true, NULL, NULL),
(132, 'marital_status', 'Lain-lain', false, NULL, NULL),
(133, 'asnaf_type', 'Fakir', false, NULL, NULL),
(134, 'asnaf_type', 'Miskin', false, NULL, NULL),
(135, 'asnaf_type', 'Bukan Fakir/Miskin', false, NULL, NULL),
(136, 'marital_status', 'Janda', false, NULL, NULL),
(137, 'marital_status', 'Bapa Tunggal', false, NULL, NULL),
(138, 'race', 'Orang Asli', false, NULL, NULL),
(139, 'race', 'Iban', false, NULL, NULL),
(140, 'race', 'Dusun', false, NULL, NULL),
(141, 'race', 'Kadazan', false, NULL, NULL),
(142, 'countries', 'Malaysia', false, NULL, NULL),
(143, 'countries', 'Afghanistan', false, NULL, NULL),
(144, 'asnaf_type', 'Muallaf', false, NULL, NULL),
(145, 'asnaf_type', 'Gharimin', false, NULL, NULL),
(146, 'asnaf_type', 'Fisabilillah', false, NULL, NULL),
(147, 'asnaf_type', 'Ibnu Sabil', false, NULL, NULL),
(148, 'asnaf_type', 'Riqab', false, NULL, NULL),
(149, 'kariah', 'MASJID AL-FIRDAUS , BANDAR BARU SELAYANG', false, 27, NULL),
(150, 'kariah', 'MASJID AL-MUTTAQIN , SELAYANG PANDANG', false, 27, NULL),
(151, 'kariah', 'MASJID AL-RIDHUAN BATU 7 1/2, HULU KELANG', false, 27, NULL),
(152, 'kariah', 'MASJID NURUL IMAN PEKAN RAWANG', false, 27, NULL),
(153, 'kariah', 'MASJID AL-SYAKIRIN , KAMPUNG BATU 5 3/4', false, 27, NULL),
(154, 'kariah', 'MASJID EH-SANIAH , SUNGAI KAMPUNG MELAYU BATU 16', false, 27, NULL),
(155, 'kariah', 'MASJID DARUL ULUM', false, 35, NULL),
(156, 'kariah', 'MASJID 29 UTARA', false, 27, NULL),
(157, 'kariah', 'MASJID SELAYANG BARU', false, 27, NULL),
(158, 'kariah', 'MASJID JAMIATUS SOLAHIAH , KAMPUNG SUNGAI TUA BARU', false, 27, NULL),
(159, 'kariah', 'MASJID JAMEK KG NAKHODA , BATU CAVES', false, 35, NULL),
(160, 'kariah', 'MASJID JAMEK AL-AMANIAH, BATU CAVES', false, 35, NULL),
(161, 'kariah', 'MASJID AN-NUR , KAMPUNG MELAYU WIRA DAMAI', false, 35, NULL),
(162, 'kariah', 'MASJID AL-KHAIRIYAH , TAMAN SERI 29', false, 35, NULL),
(163, 'kariah', 'MASJID UKAY PERDANA', false, 35, NULL),
(164, 'kariah', 'MASJID NURUL 19IAH , SUNGAI CHOH', false, 35, NULL),
(165, 'kariah', 'MASJID AL-HUDA, PAYA JARAS', false, 35, NULL),
(166, 'kariah', 'MASJID JAMEK KAMPUNG SUNGAI PLONG, KAMPUNG SUNGAI PLONG', false, 34, NULL),
(167, 'kariah', 'MASJID AL-FAIZIN , DESA JAYA', false, 34, NULL),
(168, 'kariah', 'MASJID AR-RAHIMAH , TAMAN GREENWOOD', false, 35, NULL),
(169, 'kariah', 'MASJID NURUL AMIN MERBAU SEMPAK', false, 35, NULL),
(170, 'kariah', 'MASJID JAMIUL EHSAN, KAMPUNG KUBU GAJAH', false, 35, NULL),
(171, 'kariah', 'MASJID JAMEK SUNGAI SERAI, SUNGAI SERAI', false, 35, NULL),
(172, 'kariah', 'MASJID BANDAR UTAMA BATANG KALI', false, 35, NULL),
(173, 'kariah', 'MASJID AR RAHMAN PANDAMARAN JAYA', false, 35, NULL),
(174, 'kariah', 'MASJID JAMEK IPP ( FRIM )', false, 35, NULL),
(175, 'kariah', 'MASJID AL-AMIN TAMAN TENAGA', false, 35, NULL),
(176, 'kariah', 'MASJID AL-MUJAHIDEEN, DAMANSARA UTAMA', false, 34, NULL),
(177, 'kariah', 'MASJID BANDAR BARU SG. BULOH', false, 34, NULL),
(178, 'kariah', 'MASJID KG. TUNKU', false, 34, NULL),
(179, 'kariah', 'MASJID AR-RAHMAH, DAMANSARA BARU', false, 34, NULL),
(180, 'kariah', 'MASJID SUNGAI RAMAL LUAR', false, 34, NULL),
(181, 'kariah', 'LZS-KAUNTER SELAYANG', false, 34, NULL),
(182, 'kariah', 'MASJID AL-FALAH , ULU YAM BARU', false, 34, NULL),
(183, 'kariah', 'MASJID AL-HIDAYAH DESA COALFIELDS', false, 34, NULL),
(184, 'kariah', 'MASJID ATAUFIKIAH , KAMPUNG SERI SENTOSA', false, 34, NULL),
(185, 'kariah', 'MASJID AS-SAJIDIN, BATANG KALI', false, 34, NULL),
(186, 'kariah', 'MASJID AL-MUKARRAMAH, BANDAR SRI DAMANSARA', false, 34, NULL),
(187, 'kariah', 'MASJID AS-SALAM BUKIT SENTOSA', false, 34, NULL),
(188, 'kariah', 'MASJID BANDAR BARU AMPANG', false, 34, NULL),
(189, 'kariah', 'LZS-KAUNTER PUCHONG', false, 34, NULL),
(190, 'kariah', 'MASJID NURUL HIDAYAH KAMPUNG PANDAN DALAM', false, 34, NULL),
(191, 'kariah', 'MASJID JAMIUL HUDA KG MELAYU AMPANG', false, 34, NULL),
(192, 'kariah', 'MASJID AT-TAQWA , KALUMPANG', false, 34, NULL),
(193, 'kariah', 'MASJID AMINAH AL-MUHAIRI , SEAPARK', false, 34, NULL),
(194, 'kariah', 'MASJID JAMEK KOMPLEKS PERTANIAN SERDANG', false, 34, NULL),
(195, 'education_type', 'Sijil', false, NULL, 'edu_category_0'),
(196, 'education_type', 'Lain - lain', false, NULL, 'edu_category_0'),
(197, 'education_type', 'Peringkat Rendah', false, NULL, 'edu_category_1'),
(198, 'education_type', 'STPM', false, NULL, 'edu_category_3'),
(199, 'education_type', 'Tadika', false, NULL, 'edu_category_0'),
(200, 'bantuan_kategori', 'Welfare (food ,cash)', false, NULL, NULL),
(201, 'bantuan_kategori', 'Productive(education, training,modal)', false, NULL, NULL),
(202, 'payment_status', 'Diluluskan', false, NULL, NULL),
(203, 'payment_status', 'Ditolak', false, NULL, NULL),
(204, 'payment_status', 'Dibatalkan', false, NULL, NULL),
(205, 'payment_status', 'Diberhentikan', false, NULL, NULL),
(206, 'payment_status', 'Dalam Proses', false, NULL, NULL),
(207, 'user_status', 'Dihantar', false, NULL, NULL),
(208, 'user_status', 'Pemohonan sedang disemak', false, NULL, NULL),
(209, 'user_status', 'Pemohonan sedang diproses', false, NULL, NULL),
(210, 'user_status', 'Pemohonan diluluskan', false, NULL, NULL),
(211, 'bantuan_status', 'Bantuan Dihantar', false, NULL, NULL),
(212, 'bantuan_status', 'Bantuan Disemak', false, NULL, NULL),
(213, 'bantuan_status', 'Bantuan diproses', false, NULL, NULL),
(214, 'bantuan_status', 'Bantuan Diluluskan', false, NULL, NULL),
(215, 'bantuan_status', 'Bantuan Ditolak', false, NULL, NULL),
(216, 'bantuan_status', 'Bantuan Digugurkan', false, NULL, NULL),
(217, 'user_status', 'Pemohonan ditolak', false, NULL, NULL),
(218, 'state_birth', 'Kuala Lumpur', false, NULL, NULL),
(219, 'state_birth', 'Penang', false, NULL, NULL),
(220, 'state_birth', 'Negeri Sembilan', false, NULL, NULL),
(221, 'state_birth', 'Pahang', false, NULL, NULL),
(222, 'state_birth', 'Sarawak', false, NULL, NULL),
(223, 'state_birth', 'Sabah', false, NULL, NULL),
(224, 'state_birth', 'Perak', false, NULL, NULL),
(225, 'state_birth', 'Johor', false, NULL, NULL),
(226, 'state_birth', 'Kedah', false, NULL, NULL),
(227, 'state_birth', 'Kelantan', false, NULL, NULL),
(233, 'state_birth', 'Selangor', false, NULL, NULL),
(234, 'approval_status', 'Aktif', false, NULL, NULL),
(235, 'approval_status', 'Belum Selesai', false, NULL, NULL),
(236, 'approval_status', 'Lulus', false, NULL, NULL),
(237, 'approval_status', 'Ditolak', false, NULL, NULL),
(238, 'bank_name', 'Maybank2U - Maybank2U', false, NULL, NULL),
(239, 'bank_name', 'CIMB - CIMB Bank', false, NULL, NULL),
(240, 'bank_name', 'BIMB - Bank Islam', false, NULL, NULL),
(241, 'bank_name', 'Public Bank - Public Bank', false, NULL, NULL),
(242, 'bank_name', 'Hong Leong - Hong Leong Bank', false, NULL, NULL),
(243, 'bank_name', 'RHB - RHB Bank', false, NULL, NULL),
(244, 'bank_name', 'Ambank- Ambank', false, NULL, NULL),
(245, 'bank_name', 'Bank Rakyat - Bank Rakyat', false, NULL, NULL),
(246, 'bank_name', 'Alliance - Alliance Bank', false, NULL, NULL),
(247, 'bank_name', 'Affin - Affin Bank', false, NULL, NULL),
(248, 'bank_name', 'Muamalat  - Muamalat Bank', false, NULL, NULL),
(249, 'bank_name', 'BSN - Bank Simpanan Nasional', false, NULL, NULL),
(250, 'bank_name', 'SC - Standard Chartered', false, NULL, NULL),
(251, 'bank_name', 'OCBC - OCBC Bank', false, NULL, NULL),
(252, 'bank_name', 'Agro - Agro Bank', false, NULL, NULL),
(253, 'bank_name', 'UOB - UOB Bank', false, NULL, NULL),
(254, 'bank_name', 'HSBC - HSBC Bank', false, NULL, NULL),
(255, 'bank_name', 'KFH - KFH Bank', false, NULL, NULL),
(256, 'bank_name', 'CIMB Islamic  - CIMB Islamic Bank', false, NULL, NULL),
(257, 'bank_name', 'Maybank2E - Maybank2E', false, NULL, NULL),
(258, 'organization_type', 'Pembekal / vendor - contoh farmasi', false, NULL, NULL),
(259, 'organization_type', 'Agensi / institusi - contoh NGO, Sekolah, IPT, Masjid/Surau', false, NULL, NULL),
(260, 'organization_type', 'Hospital', false, NULL, NULL),
(261, 'organization_type', 'Pusat Dialisis', false, NULL, NULL),
(262, 'organization_type', 'Kontraktor', false, NULL, NULL),
(263, 'organization_type', 'Contributor Agihan Semula', false, NULL, NULL),
(264, 'organization_category', 'Kerajaan', false, NULL, NULL),
(265, 'organization_category', 'Swasta', false, NULL, NULL),
(266, 'organization_category', 'NGO', false, NULL, NULL),
(267, 'organization_category', 'Lain-Lain', false, NULL, NULL),
(268, 'job_types', 'Kehilangan Kerja', false, NULL, NULL),
(269, 'tahap_kesihatan', 'Sihat', false, NULL, NULL),
(270, 'tahap_kesihatan', 'Sakit', false, NULL, NULL),
(271, 'tahap_kesihatan', 'Terlantar', false, NULL, NULL),
(272, 'tahap_kesihatan', 'Kronik', false, NULL, NULL),
(273, 'relationship', 'Anak', false, NULL, NULL)
ON CONFLICT (lookup_id) DO NOTHING;
